import { Box } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import HomePage from "view/Home/index";
const Home: NextPage = () => {
    return (
        <Box
            sx={{
                bgcolor: "#0a2a34",
                minHeight: "100vh",
            }}
        >
            <Head>
                <title>IFO</title>
                <meta name="description" content="Generated by create next wagmi dapp" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomePage></HomePage>
        </Box>
    );
};

export default Home;
