import type { NextPage } from "next";
import Head from "next/head";
import HomePage from "view/Home/index";
const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>IFO</title>
                <meta name="description" content="Generated by create next wagmi dapp" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomePage></HomePage>
        </div>
    );
};

export default Home;
